#!/bin/bash
intHDD=$( lsblk|grep SWAP|cut -c 7,8,9 )
while ! [[ $choice =~ ^sd[a-z]$ ]]
do
	clear
	echo "Check DCO and HPA status of a SATA device."
	echo ""
	lsblk|grep -v $intHDD|grep -v sr0
	echo ""
	read -p "Please Enter a device choice from the above list (sdb, sdc, sdd etc.): " choice
	echo ""
done
if [[ $choice = $intHDD ]]
then
	echo "You have chosen the internal HDD.  Aborting..."
	exit 1
elif [[ $( lsblk|grep $choice ) = '' ]]
then
	echo "No block device '$choice' found.  Aborting..."
	exit 1
else
	if [[ $( hdparm -I /dev/$choice 2>&1|grep SG_IO ) != '' ]]
	then
		echo "Device doesn't appear to support ATA commands."
		echo "Aborting..."
		exit 1
	fi
	echo "Checking for HPA (Host Protected Area)..."
	hdparm -N /dev/$choice
	echo ""
	echo "Checking DCO (Device Configuration Overlay)..."
	hdparm --dco-identify /dev/$choice
fi

